name: Generate the relation of gentoo-zh packages
on:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Fetch gentoo-zh repo
        run: git clone https://github.com/microcai/gentoo-zh.git gentoo-zh
      - name: Update packages relation
        id: update_relation
        shell: bash
        run: ./update-relation.sh
      - name: Push changes
        if: ${{ steps.update_relation.outputs.state == 'changed' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Post to pastebin
        if: ${{ steps.update_relation.outputs.state == 'changed' }}
        shell: bash
        env:
          myuuid: ${{ secrets.UUID }}
        run: curl -X PUT -F "c=@-" "http://fars.ee/$myuuid" <relation.md

